# -*- coding: utf-8 -*-
"""Clark Wright Savings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAZfDPmxTiCasXwsqjbsnfJidDX5uI0I
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# read node data in coordinate (x,y) format
nodes = pd.read_excel('/content/Dataset.xlsx', index_col = 'node',sheet_name = 'Demand')
nodes

nodes.rename(columns={"Jarak dari Pusat":'d0'}, inplace = True)
nodes

node_number = len(nodes.index) - 1
nodes.head()

# read pairwise distance
pw = pd.read_excel('/content/Dataset.xlsx', index_col = 'Unnamed: 0',sheet_name = 'Matriks Berpasangan')
pw.head()
pw.index.rename('',inplace = True)
pw

# calculate savings for each link
savings = dict()
savings

for r in pw.index:
    for c in pw.columns:
        if int(c) != int(r):
            a = max(int(r), int(c))
            b = min(int(r), int(c))
            key = '(' + str(a) + ',' + str(b) + ')'
            savings[key] = nodes['d0'][int(r)] + nodes['d0'][int(c)] - pw[c][r]

# put savings in a pandas dataframe, and sort by descending
sv = pd.DataFrame.from_dict(savings, orient = 'index')
sv.rename(columns = {0:'saving'}, inplace = True)
sv.sort_values(by = ['saving'], ascending = False, inplace = True)
sv.head()

# convert link string to link list to handle saving's key, i.e. str(10, 6) to (10, 6)
def get_node(link):
    link = link[1:]
    link = link[:-1]
    nodes = link.split(',')
    return [int(nodes[0]), int(nodes[1])]

# determine if a node is interior to a route
def interior(node, route):
    try:
        i = route.index(node)
        # adjacent to depot, not interior
        if i == 0 or i == (len(route) - 1):
            label = False
        else:
            label = True
    except:
        label = False

    return label

# merge two routes with a connection link
def merge(route0, route1, link):
    if route0.index(link[0]) != (len(route0) - 1):
        route0.reverse()

    if route1.index(link[1]) != 0:
        route1.reverse()

    return route0 + route1

# sum up to obtain the total passengers belonging to a route
def sum_cap(route):
    sum_cap = 0
    for node in route:
        sum_cap += nodes.demand[node]
    return sum_cap

# determine 4 things:
# 1. if the link in any route in routes -> determined by if count_in > 0
# 2. if yes, which node is in the route -> returned to node_sel
# 3. if yes, which route is the node belongs to -> returned to route id: i_route
# 4. are both of the nodes in the same route? -> overlap = 1, yes; otherwise, no
def which_route(link, routes):
    # assume nodes are not in any route
    node_sel = list()
    i_route = [-1, -1]
    count_in = 0

    for route in routes:
        for node in link:
            try:
                route.index(node)
                i_route[count_in] = routes.index(route)
                node_sel.append(node)
                count_in += 1
            except:
                pass

    if i_route[0] == i_route[1]:
        overlap = 1
    else:
        overlap = 0

    return node_sel, count_in, i_route, overlap

# create empty routes
routes = list()

# if there is any remaining customer to be served
remaining = True

# define capacity of the vehicle
cap = 20

# record steps
step = 0

# get a list of nodes, excluding the depot
node_list = list(nodes.index)
node_list.remove(0)

# run through each link in the saving list
for link in sv.index:
    step += 1
    if remaining:

        print('step ', step, ':')

        link = get_node(link)
        node_sel, num_in, i_route, overlap = which_route(link, routes)

        # condition a. Either, neither i nor j have already been assigned to a route,
        # ...in which case a new route is initiated including both i and j.
        if num_in == 0:
            if sum_cap(link) <= cap:
                routes.append(link)
                node_list.remove(link[0])
                node_list.remove(link[1])
                print('\t','Link ', link, ' fulfills criteria a), so it is created as a new route')
            else:
                print('\t','Though Link ', link, ' fulfills criteria a), it exceeds maximum load, so skip this link.')

        # condition b. Or, exactly one of the two nodes (i or j) has already been included
        # ...in an existing route and that point is not interior to that route
        # ...(a point is interior to a route if it is not adjacent to the depot D in the order of traversal of nodes),
        # ...in which case the link (i, j) is added to that same route.
        elif num_in == 1:
            n_sel = node_sel[0]
            i_rt = i_route[0]
            position = routes[i_rt].index(n_sel)
            link_temp = link.copy()
            link_temp.remove(n_sel)
            node = link_temp[0]

            cond1 = (not interior(n_sel, routes[i_rt]))
            cond2 = (sum_cap(routes[i_rt] + [node]) <= cap)

            if cond1:
                if cond2:
                    print('\t','Link ', link, ' fulfills criteria b), so a new node is added to route ', routes[i_rt], '.')
                    if position == 0:
                        routes[i_rt].insert(0, node)
                    else:
                        routes[i_rt].append(node)
                    node_list.remove(node)
                else:
                    print('\t','Though Link ', link, ' fulfills criteria b), it exceeds maximum load, so skip this link.')
                    continue
            else:
                print('\t','For Link ', link, ', node ', n_sel, ' is interior to route ', routes[i_rt], ', so skip this link')
                continue

        # condition c. Or, both i and j have already been included in two different existing routes
        # ...and neither point is interior to its route, in which case the two routes are merged.
        else:
            if overlap == 0:
                cond1 = (not interior(node_sel[0], routes[i_route[0]]))
                cond2 = (not interior(node_sel[1], routes[i_route[1]]))
                cond3 = (sum_cap(routes[i_route[0]] + routes[i_route[1]]) <= cap)

                if cond1 and cond2:
                    if cond3:
                        route_temp = merge(routes[i_route[0]], routes[i_route[1]], node_sel)
                        temp1 = routes[i_route[0]]
                        temp2 = routes[i_route[1]]
                        routes.remove(temp1)
                        routes.remove(temp2)
                        routes.append(route_temp)
                        try:
                            node_list.remove(link[0])
                            node_list.remove(link[1])
                        except:
                            #print('\t', f"Node {link[0]} or {link[1]} has been removed in a previous step.")
                            pass
                        print('\t','Link ', link, ' fulfills criteria c), so route ', temp1, ' and route ', temp2, ' are merged')
                    else:
                        print('\t','Though Link ', link, ' fulfills criteria c), it exceeds maximum load, so skip this link.')
                        continue
                else:
                    print('\t','For link ', link, ', Two nodes are found in two different routes, but not all the nodes fulfill interior requirement, so skip this link')
                    continue
            else:
                print('\t','Link ', link, ' is already included in the routes')
                continue

        for route in routes:
            print('\t','route: ', route, ' with load ', sum_cap(route))
    else:
        print('-------')
        print('All nodes are included in the routes, algorithm closed')
        break

    remaining = bool(len(node_list) > 0)

# check if any node is left, assign to a unique route
for node_o in node_list:
    routes.append([node_o])

# add depot to the routes
for route in routes:
    route.insert(0,0)
    route.append(0)

print('------')
print('Routes found are: ')

routes

routes

# prompt: Dari masing-masing rute dalam routes yang telah didapat, hitung total jarak dari masing-masing rute berdasarkan d0 pada nodes.

route_distances = []

for route in routes:
    total_distance = 0
    for i in range(len(route) - 3):
        current_node = route[i + 1]
        next_node = route[i + 2]
        distance = pw.loc[current_node, next_node]
        total_distance += distance + nodes['d0'][current_node] + nodes['d0'][next_node]
    route_distances.append(total_distance)

for i, route in enumerate(routes):
    print(f"Route {i + 1}: {route} has a total distance of {route_distances[i]}")

# Menampilkan peta rute
# rute perjalanan
rute1 = routes[0]
rute2 = routes[1]
rute3 = routes[2]
rute4 = routes[3]
rute5 = routes[4]
rute6 = routes[5]
rute7 = routes[6]

# plot rute perjalanan 1
plt.scatter(nodes['Longitude'][0], nodes['Latitude'][0], label='EWM')

for i in range(len(rute1) - 1):
  plt.plot([nodes['Longitude'][rute1[i]], nodes['Longitude'][rute1[i+1]]], [nodes['Latitude'][rute1[i]], nodes['Latitude'][rute1[i+1]]], 'r')

plt.scatter(nodes['Longitude'][1], nodes['Latitude'][1], label='C1')
plt.scatter(nodes['Longitude'][2], nodes['Latitude'][2], label='C2')
plt.scatter(nodes['Longitude'][3], nodes['Latitude'][3], label='C3')
plt.scatter(nodes['Longitude'][4], nodes['Latitude'][4], label='C4')
plt.scatter(nodes['Longitude'][5], nodes['Latitude'][5], label='C5')
plt.scatter(nodes['Longitude'][6], nodes['Latitude'][6], label='C6')
plt.scatter(nodes['Longitude'][7], nodes['Latitude'][7], label='C7')
plt.scatter(nodes['Longitude'][8], nodes['Latitude'][8], label='C8')
plt.scatter(nodes['Longitude'][9], nodes['Latitude'][9], label='C9')
plt.scatter(nodes['Longitude'][10], nodes['Latitude'][10], label='C10')
plt.scatter(nodes['Longitude'][11], nodes['Latitude'][11], label='C11')
plt.scatter(nodes['Longitude'][12], nodes['Latitude'][12], label='C12')
plt.scatter(nodes['Longitude'][13], nodes['Latitude'][13], label='C13')
plt.scatter(nodes['Longitude'][14], nodes['Latitude'][14], label='C14')
plt.scatter(nodes['Longitude'][15], nodes['Latitude'][15], label='C15')
plt.scatter(nodes['Longitude'][16], nodes['Latitude'][16], label='C16')
plt.scatter(nodes['Longitude'][17], nodes['Latitude'][17], label='C17')
plt.scatter(nodes['Longitude'][18], nodes['Latitude'][18], label='C18')
plt.scatter(nodes['Longitude'][19], nodes['Latitude'][19], label='C19')
plt.scatter(nodes['Longitude'][20], nodes['Latitude'][20], label='C20')
plt.legend()
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Rute Perjalanan 1')
plt.show()

# plot rute perjalanan 2
plt.scatter(nodes['Longitude'][0], nodes['Latitude'][0], label='EWM')

for i in range(len(rute2) - 1):
  plt.plot([nodes['Longitude'][rute2[i]], nodes['Longitude'][rute2[i+1]]], [nodes['Latitude'][rute2[i]], nodes['Latitude'][rute2[i+1]]], 'r')

plt.scatter(nodes['Longitude'][1], nodes['Latitude'][1], label='C1')
plt.scatter(nodes['Longitude'][2], nodes['Latitude'][2], label='C2')
plt.scatter(nodes['Longitude'][3], nodes['Latitude'][3], label='C3')
plt.scatter(nodes['Longitude'][4], nodes['Latitude'][4], label='C4')
plt.scatter(nodes['Longitude'][5], nodes['Latitude'][5], label='C5')
plt.scatter(nodes['Longitude'][6], nodes['Latitude'][6], label='C6')
plt.scatter(nodes['Longitude'][7], nodes['Latitude'][7], label='C7')
plt.scatter(nodes['Longitude'][8], nodes['Latitude'][8], label='C8')
plt.scatter(nodes['Longitude'][9], nodes['Latitude'][9], label='C9')
plt.scatter(nodes['Longitude'][10], nodes['Latitude'][10], label='C10')
plt.scatter(nodes['Longitude'][11], nodes['Latitude'][11], label='C11')
plt.scatter(nodes['Longitude'][12], nodes['Latitude'][12], label='C12')
plt.scatter(nodes['Longitude'][13], nodes['Latitude'][13], label='C13')
plt.scatter(nodes['Longitude'][14], nodes['Latitude'][14], label='C14')
plt.scatter(nodes['Longitude'][15], nodes['Latitude'][15], label='C15')
plt.scatter(nodes['Longitude'][16], nodes['Latitude'][16], label='C16')
plt.scatter(nodes['Longitude'][17], nodes['Latitude'][17], label='C17')
plt.scatter(nodes['Longitude'][18], nodes['Latitude'][18], label='C18')
plt.scatter(nodes['Longitude'][19], nodes['Latitude'][19], label='C19')
plt.scatter(nodes['Longitude'][20], nodes['Latitude'][20], label='C20')
plt.legend()
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Rute Perjalanan 2')
plt.show()

# plot rute perjalanan 3
plt.scatter(nodes['Longitude'][0], nodes['Latitude'][0], label='EWM')

for i in range(len(rute3) - 1):
  plt.plot([nodes['Longitude'][rute3[i]], nodes['Longitude'][rute3[i+1]]], [nodes['Latitude'][rute3[i]], nodes['Latitude'][rute3[i+1]]], 'r')

plt.scatter(nodes['Longitude'][1], nodes['Latitude'][1], label='C1')
plt.scatter(nodes['Longitude'][2], nodes['Latitude'][2], label='C2')
plt.scatter(nodes['Longitude'][3], nodes['Latitude'][3], label='C3')
plt.scatter(nodes['Longitude'][4], nodes['Latitude'][4], label='C4')
plt.scatter(nodes['Longitude'][5], nodes['Latitude'][5], label='C5')
plt.scatter(nodes['Longitude'][6], nodes['Latitude'][6], label='C6')
plt.scatter(nodes['Longitude'][7], nodes['Latitude'][7], label='C7')
plt.scatter(nodes['Longitude'][8], nodes['Latitude'][8], label='C8')
plt.scatter(nodes['Longitude'][9], nodes['Latitude'][9], label='C9')
plt.scatter(nodes['Longitude'][10], nodes['Latitude'][10], label='C10')
plt.scatter(nodes['Longitude'][11], nodes['Latitude'][11], label='C11')
plt.scatter(nodes['Longitude'][12], nodes['Latitude'][12], label='C12')
plt.scatter(nodes['Longitude'][13], nodes['Latitude'][13], label='C13')
plt.scatter(nodes['Longitude'][14], nodes['Latitude'][14], label='C14')
plt.scatter(nodes['Longitude'][15], nodes['Latitude'][15], label='C15')
plt.scatter(nodes['Longitude'][16], nodes['Latitude'][16], label='C16')
plt.scatter(nodes['Longitude'][17], nodes['Latitude'][17], label='C17')
plt.scatter(nodes['Longitude'][18], nodes['Latitude'][18], label='C18')
plt.scatter(nodes['Longitude'][19], nodes['Latitude'][19], label='C19')
plt.scatter(nodes['Longitude'][20], nodes['Latitude'][20], label='C20')
plt.legend()
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Rute Perjalanan 3')
plt.show()

# plot rute perjalanan 4
plt.scatter(nodes['Longitude'][0], nodes['Latitude'][0], label='EWM')

for i in range(len(rute4) - 1):
  plt.plot([nodes['Longitude'][rute4[i]], nodes['Longitude'][rute4[i+1]]], [nodes['Latitude'][rute4[i]], nodes['Latitude'][rute4[i+1]]], 'r')

plt.scatter(nodes['Longitude'][1], nodes['Latitude'][1], label='C1')
plt.scatter(nodes['Longitude'][2], nodes['Latitude'][2], label='C2')
plt.scatter(nodes['Longitude'][3], nodes['Latitude'][3], label='C3')
plt.scatter(nodes['Longitude'][4], nodes['Latitude'][4], label='C4')
plt.scatter(nodes['Longitude'][5], nodes['Latitude'][5], label='C5')
plt.scatter(nodes['Longitude'][6], nodes['Latitude'][6], label='C6')
plt.scatter(nodes['Longitude'][7], nodes['Latitude'][7], label='C7')
plt.scatter(nodes['Longitude'][8], nodes['Latitude'][8], label='C8')
plt.scatter(nodes['Longitude'][9], nodes['Latitude'][9], label='C9')
plt.scatter(nodes['Longitude'][10], nodes['Latitude'][10], label='C10')
plt.scatter(nodes['Longitude'][11], nodes['Latitude'][11], label='C11')
plt.scatter(nodes['Longitude'][12], nodes['Latitude'][12], label='C12')
plt.scatter(nodes['Longitude'][13], nodes['Latitude'][13], label='C13')
plt.scatter(nodes['Longitude'][14], nodes['Latitude'][14], label='C14')
plt.scatter(nodes['Longitude'][15], nodes['Latitude'][15], label='C15')
plt.scatter(nodes['Longitude'][16], nodes['Latitude'][16], label='C16')
plt.scatter(nodes['Longitude'][17], nodes['Latitude'][17], label='C17')
plt.scatter(nodes['Longitude'][18], nodes['Latitude'][18], label='C18')
plt.scatter(nodes['Longitude'][19], nodes['Latitude'][19], label='C19')
plt.scatter(nodes['Longitude'][20], nodes['Latitude'][20], label='C20')
plt.legend()
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Rute Perjalanan 4')
plt.show()

# plot rute perjalanan 5
plt.scatter(nodes['Longitude'][0], nodes['Latitude'][0], label='EWM')

for i in range(len(rute5) - 1):
  plt.plot([nodes['Longitude'][rute5[i]], nodes['Longitude'][rute5[i+1]]], [nodes['Latitude'][rute5[i]], nodes['Latitude'][rute5[i+1]]], 'r')

plt.scatter(nodes['Longitude'][1], nodes['Latitude'][1], label='C1')
plt.scatter(nodes['Longitude'][2], nodes['Latitude'][2], label='C2')
plt.scatter(nodes['Longitude'][3], nodes['Latitude'][3], label='C3')
plt.scatter(nodes['Longitude'][4], nodes['Latitude'][4], label='C4')
plt.scatter(nodes['Longitude'][5], nodes['Latitude'][5], label='C5')
plt.scatter(nodes['Longitude'][6], nodes['Latitude'][6], label='C6')
plt.scatter(nodes['Longitude'][7], nodes['Latitude'][7], label='C7')
plt.scatter(nodes['Longitude'][8], nodes['Latitude'][8], label='C8')
plt.scatter(nodes['Longitude'][9], nodes['Latitude'][9], label='C9')
plt.scatter(nodes['Longitude'][10], nodes['Latitude'][10], label='C10')
plt.scatter(nodes['Longitude'][11], nodes['Latitude'][11], label='C11')
plt.scatter(nodes['Longitude'][12], nodes['Latitude'][12], label='C12')
plt.scatter(nodes['Longitude'][13], nodes['Latitude'][13], label='C13')
plt.scatter(nodes['Longitude'][14], nodes['Latitude'][14], label='C14')
plt.scatter(nodes['Longitude'][15], nodes['Latitude'][15], label='C15')
plt.scatter(nodes['Longitude'][16], nodes['Latitude'][16], label='C16')
plt.scatter(nodes['Longitude'][17], nodes['Latitude'][17], label='C17')
plt.scatter(nodes['Longitude'][18], nodes['Latitude'][18], label='C18')
plt.scatter(nodes['Longitude'][19], nodes['Latitude'][19], label='C19')
plt.scatter(nodes['Longitude'][20], nodes['Latitude'][20], label='C20')
plt.legend()
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Rute Perjalanan 5')
plt.show()

# plot rute perjalanan 6
plt.scatter(nodes['Longitude'][0], nodes['Latitude'][0], label='EWM')

for i in range(len(rute6) - 1):
  plt.plot([nodes['Longitude'][rute6[i]], nodes['Longitude'][rute6[i+1]]], [nodes['Latitude'][rute6[i]], nodes['Latitude'][rute6[i+1]]], 'r')

plt.scatter(nodes['Longitude'][1], nodes['Latitude'][1], label='C1')
plt.scatter(nodes['Longitude'][2], nodes['Latitude'][2], label='C2')
plt.scatter(nodes['Longitude'][3], nodes['Latitude'][3], label='C3')
plt.scatter(nodes['Longitude'][4], nodes['Latitude'][4], label='C4')
plt.scatter(nodes['Longitude'][5], nodes['Latitude'][5], label='C5')
plt.scatter(nodes['Longitude'][6], nodes['Latitude'][6], label='C6')
plt.scatter(nodes['Longitude'][7], nodes['Latitude'][7], label='C7')
plt.scatter(nodes['Longitude'][8], nodes['Latitude'][8], label='C8')
plt.scatter(nodes['Longitude'][9], nodes['Latitude'][9], label='C9')
plt.scatter(nodes['Longitude'][10], nodes['Latitude'][10], label='C10')
plt.scatter(nodes['Longitude'][11], nodes['Latitude'][11], label='C11')
plt.scatter(nodes['Longitude'][12], nodes['Latitude'][12], label='C12')
plt.scatter(nodes['Longitude'][13], nodes['Latitude'][13], label='C13')
plt.scatter(nodes['Longitude'][14], nodes['Latitude'][14], label='C14')
plt.scatter(nodes['Longitude'][15], nodes['Latitude'][15], label='C15')
plt.scatter(nodes['Longitude'][16], nodes['Latitude'][16], label='C16')
plt.scatter(nodes['Longitude'][17], nodes['Latitude'][17], label='C17')
plt.scatter(nodes['Longitude'][18], nodes['Latitude'][18], label='C18')
plt.scatter(nodes['Longitude'][19], nodes['Latitude'][19], label='C19')
plt.scatter(nodes['Longitude'][20], nodes['Latitude'][20], label='C20')
plt.legend()
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Rute Perjalanan 6')
plt.show()

# plot rute perjalanan 7
plt.scatter(nodes['Longitude'][0], nodes['Latitude'][0], label='EWM')

for i in range(len(rute7) - 1):
  plt.plot([nodes['Longitude'][rute7[i]], nodes['Longitude'][rute7[i+1]]], [nodes['Latitude'][rute7[i]], nodes['Latitude'][rute7[i+1]]], 'r')

plt.scatter(nodes['Longitude'][1], nodes['Latitude'][1], label='C1')
plt.scatter(nodes['Longitude'][2], nodes['Latitude'][2], label='C2')
plt.scatter(nodes['Longitude'][3], nodes['Latitude'][3], label='C3')
plt.scatter(nodes['Longitude'][4], nodes['Latitude'][4], label='C4')
plt.scatter(nodes['Longitude'][5], nodes['Latitude'][5], label='C5')
plt.scatter(nodes['Longitude'][6], nodes['Latitude'][6], label='C6')
plt.scatter(nodes['Longitude'][7], nodes['Latitude'][7], label='C7')
plt.scatter(nodes['Longitude'][8], nodes['Latitude'][8], label='C8')
plt.scatter(nodes['Longitude'][9], nodes['Latitude'][9], label='C9')
plt.scatter(nodes['Longitude'][10], nodes['Latitude'][10], label='C10')
plt.scatter(nodes['Longitude'][11], nodes['Latitude'][11], label='C11')
plt.scatter(nodes['Longitude'][12], nodes['Latitude'][12], label='C12')
plt.scatter(nodes['Longitude'][13], nodes['Latitude'][13], label='C13')
plt.scatter(nodes['Longitude'][14], nodes['Latitude'][14], label='C14')
plt.scatter(nodes['Longitude'][15], nodes['Latitude'][15], label='C15')
plt.scatter(nodes['Longitude'][16], nodes['Latitude'][16], label='C16')
plt.scatter(nodes['Longitude'][17], nodes['Latitude'][17], label='C17')
plt.scatter(nodes['Longitude'][18], nodes['Latitude'][18], label='C18')
plt.scatter(nodes['Longitude'][19], nodes['Latitude'][19], label='C19')
plt.scatter(nodes['Longitude'][20], nodes['Latitude'][20], label='C20')
plt.legend()
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Rute Perjalanan 7')
plt.show()

# plot seluruh rute perjalanan
plt.scatter(nodes['Longitude'][0], nodes['Latitude'][0], label='EWM')

for i in range(len(rute1) - 1):
  plt.plot([nodes['Longitude'][rute1[i]], nodes['Longitude'][rute1[i+1]]], [nodes['Latitude'][rute1[i]], nodes['Latitude'][rute1[i+1]]], 'r')
for i in range(len(rute2) - 1):
  plt.plot([nodes['Longitude'][rute2[i]], nodes['Longitude'][rute2[i+1]]], [nodes['Latitude'][rute2[i]], nodes['Latitude'][rute2[i+1]]], 'b')
for i in range(len(rute3) - 1):
  plt.plot([nodes['Longitude'][rute3[i]], nodes['Longitude'][rute3[i+1]]], [nodes['Latitude'][rute3[i]], nodes['Latitude'][rute3[i+1]]], 'k')
for i in range(len(rute4) - 1):
  plt.plot([nodes['Longitude'][rute4[i]], nodes['Longitude'][rute4[i+1]]], [nodes['Latitude'][rute4[i]], nodes['Latitude'][rute4[i+1]]], 'y')
for i in range(len(rute5) - 1):
  plt.plot([nodes['Longitude'][rute5[i]], nodes['Longitude'][rute5[i+1]]], [nodes['Latitude'][rute5[i]], nodes['Latitude'][rute5[i+1]]], 'g')
for i in range(len(rute6) - 1):
  plt.plot([nodes['Longitude'][rute6[i]], nodes['Longitude'][rute6[i+1]]], [nodes['Latitude'][rute6[i]], nodes['Latitude'][rute6[i+1]]], 'p')
for i in range(len(rute7) - 1):
  plt.plot([nodes['Longitude'][rute7[i]], nodes['Longitude'][rute7[i+1]]], [nodes['Latitude'][rute7[i]], nodes['Latitude'][rute7[i+1]]], 'o')

plt.scatter(nodes['Longitude'][1], nodes['Latitude'][1], label='C1')
plt.scatter(nodes['Longitude'][2], nodes['Latitude'][2], label='C2')
plt.scatter(nodes['Longitude'][3], nodes['Latitude'][3], label='C3')
plt.scatter(nodes['Longitude'][4], nodes['Latitude'][4], label='C4')
plt.scatter(nodes['Longitude'][5], nodes['Latitude'][5], label='C5')
plt.scatter(nodes['Longitude'][6], nodes['Latitude'][6], label='C6')
plt.scatter(nodes['Longitude'][7], nodes['Latitude'][7], label='C7')
plt.scatter(nodes['Longitude'][8], nodes['Latitude'][8], label='C8')
plt.scatter(nodes['Longitude'][9], nodes['Latitude'][9], label='C9')
plt.scatter(nodes['Longitude'][10], nodes['Latitude'][10], label='C10')
plt.scatter(nodes['Longitude'][11], nodes['Latitude'][11], label='C11')
plt.scatter(nodes['Longitude'][12], nodes['Latitude'][12], label='C12')
plt.scatter(nodes['Longitude'][13], nodes['Latitude'][13], label='C13')
plt.scatter(nodes['Longitude'][14], nodes['Latitude'][14], label='C14')
plt.scatter(nodes['Longitude'][15], nodes['Latitude'][15], label='C15')
plt.scatter(nodes['Longitude'][16], nodes['Latitude'][16], label='C16')
plt.scatter(nodes['Longitude'][17], nodes['Latitude'][17], label='C17')
plt.scatter(nodes['Longitude'][18], nodes['Latitude'][18], label='C18')
plt.scatter(nodes['Longitude'][19], nodes['Latitude'][19], label='C19')
plt.scatter(nodes['Longitude'][20], nodes['Latitude'][20], label='C20')
plt.legend(fontsize='x-small')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Rute Seluruh Perjalanan')
plt.show()